/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testAddReview() {
        Restaurant restaurant = new Restaurant("Pizza Palace");
        Review review = new Review("Great pizza!", "Alice", 5, restaurant);
        assertEquals(1, restaurant.getReviews().size());
        assertEquals(review, restaurant.getReviews().get(0));
        System.out.println("testAddReview passed");

    }
    @Test
    public void testAddDuplicateReview() {
        Restaurant restaurant = new Restaurant("Pizza Palace");
        Review review1 = new Review("Great pizza!", "Alice", 5, restaurant);
        Review review2 = new Review("Bad pizza!", "Alice", 1, restaurant);
        assertEquals(1, restaurant.getReviews().size());
        assertEquals(review1, restaurant.getReviews().get(0));
        assertNotEquals(review2, restaurant.getReviews().get(0));
        System.out.println("testAddDuplicateReview passed");
    }

    @Test
    public void testCalculateAverageRating() {
        Restaurant restaurant = new Restaurant("Pizza Palace");
        Review review1 = new Review("Great pizza!", "Alice", 5, restaurant);
        Review review2 = new Review("Decent pizza.", "Bob", 3, restaurant);
        Review review3 = new Review("Bad pizza!", "Charlie", 1, restaurant);
        assertEquals(3, restaurant.getReviews().size());
        assertEquals((5 + 3 + 1) / 3.0, restaurant.getAverageRating());
        System.out.println("testCalculateAverageRating passed");
    }

}
