/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.util.List;
import java.util.Arrays;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testAnalyzeWeatherData() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String expectedOutput = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n";
        String actualOutput = App.analyzeWeatherData(weeklyMonthTemperatures);
        assertEquals(expectedOutput, actualOutput);
    }
    @Test void testTally() {
            List<String> votes = Arrays.asList("A", "B", "C", "A", "A", "B", "B", "C", "C", "C", "D");
            String result = App.tally(votes);
            assertEquals("C received the most votes with 4 votes.", result);

        }


    }

